---
- hosts: cluster
  become: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: gnupg, tags: ['gnupg']}
    - { role: microcode, tags: ['microcode'], when: "'GenuineIntel' in ansible_processor" }
    - { role: mirrorlist, tags: ['mirrorlist']}
    - { role: ssh, tags: ['ssh'] }
    - { role: hardened, tags: ['hardened'], when: 'hardened is defined' }
    - { role: wifi, tags: ['wifi'], when: 'wifi is defined' }
    - { role: mail, tags: ['mail'], when: 'msmtp is defined' }
    - { role: mdadm, tags: ['mdadm'] }
    - { role: docker, tags: ['docker'] }
    - { role: restic, tags: ['restic'] }

  # TODO(ppacher): remove the prompt and switch to vaults
  # for multi-user systems.
  vars_prompt:
    - name: user_password
      prompt: "Enter desired user password"