---
- hosts: all
  become: yes
  roles:
    - {role: base, tags: ['base']}
    - {role: users, tags: ['users']}
    - {role: gnupg, tags: ['gnupg']}
    - {role: microcode, tags: ['microcode']}
    - {role: mirrorlist, tags: ['mirrorlist']}
    - {role: ssh, tags: ['ssh']}
    - {role: wifi, tags: ['wifi'], when: wifi is defined}
    - {role: mail, tags: ['mail', 'msmtp'], when: msmtp is defined}
    - {role: mdadm, tags: ['mdadm']}
    - {role: hardened, tags: ['hardened'], when: hardened is defined}

- hosts: server
  become: yes
  roles:
    - role: hetzner-storagebox
      when: backups is defined and hetzner is defined
      tags: ['hetzner-storagebox']
  
    - role: restic
      when: backups is defined
      tags: ['restic']
    
- hosts: htpc
  become: yes
  tasks:
    - include_role:
        name: "users"
        tasks_from: "configure_user.yml"
      vars:
        item: "{{ htpc.user }}"
      when: htpc.user is defined
  roles:
    - role: gdm-autologin
      when: htpc.user is defined and htpc.user.autologin == True
      vars:
        autologin: "{{ htpc.user.autologin }}"
      tags: ['gdm']

    - role: librespot
      when: librespot is defined and htpc.user is defined
      tags: ['librespot']
      vars:
        librespot_user: "{{ htpc.user.name }}"
