---
- name: Install gdm
  pacman:
    name: gdm
    state: present
  tags:
    - gdm
    
- name: Enable and start GDM login manager
  service:
    name: gdm.service
    enabled: yes
    state: started
  tags: 
    - gdm
    
- name: Enable autologin using GDM
  community.general.ini_file:
    path: /etc/gdb/custom.conf
    section: daemon
    option: AutomaticLoginEnabled
    value: "true"
    mode: '0644'
  when: autologin is defined
  notify:
    - restart gdm
  tags: 
    - gdm

- name: Configure autologin for  {{ autologin }}
  community.general.ini_file:
    path: /etc/gdb/custom.conf
    section: daemon
    option: AutomaticLogin
    value: "{{ autologin }}"
    mode: '0644'
  when: autologin is defined
  notify:
    - restart gdm
  tags: 
    - gdm
