---
- name: restart paccache
  service:
    name: paccache.timer
    state: restarted
  
- name: stop systemd per-user instance
  service:
    name: "user@{{ item.uid }}"
    state: stopped
  loop: "{{ users }}"
  loop_control:
    label: "{{ item.name }}"

- name: generate locales
  command: locale-gen