#hetzner:
#  storageboxes:
#    - u227722

#backups:
#  - name: test
#    paths: "/home/paz"
#    repository: sftp:u227722.your-storagebox.de:{{ hostname | default(inventory_hostname) }}
#    password: "test"
#    excludes: ""
#    init: True
#    retention:
#      days: 4
#      weeks: 4
#      months: 6
#      years: 3
