hetzner:
  storageboxes:
    - u123456

backups:
  - name: test
    paths: "/home/user"
    repository: sftp:u123456.your-storagebox.de:{{ hostname | default(inventory_hostname) }}
    password: "test"
    excludes: ""
    init: True
    retention:
      days: 4
      weeks: 4
      months: 6
      years: 3
