users:
  - name: user
    group: user
    groups: [ wheel ]
    shell: /usr/bin/zsh
    email: user@domain.tld
    dotfiles: 
    enable_gnupg_agent: True
    passwordless_sudo: True
    ssh_pub_keys:
    log:
      dir: log
      rotate: 8
      
timezone: Europe/Vienna
      
ssh:
  port: 22
    
aur:
  packages:
    - kitty-terminfo
    - bitwarden-cli
        
base_packages:
    - base-devel
    - man-db
    - man-pages
    - pacman-contrib
    - dmidecode
    - fwupd
    - tmux
    - git
    - rsync
    - coreutils
    - moreutils
    - dateutils
    - bc
    - arch-wiki-lite
    - arch-wiki-docs
    - pv
    - jq
    - fzf
    - cpulimit
    - bat
    - exa
    - neovim
    - diff-so-fancy
    - htop