---
- name: Install OpenSSH
  pacman:
    name: openssh
    state: present
  tags:
    - ssh

- name: OpenSSH daemon configuration
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify:
    - restart sshd
  tags:
    - ssh

- name: Enable OpenSSH daemon
  service:
    name: sshd.service
    enabled: yes
    state: started
  tags:
    - ssh
    
- name: Install Mosh
  pacman:
    name: mosh
    state: present

- import_tasks: ./root_ssh_config.yml