---
- name: Provide caddy image builder
  include_role: 
    name: image_builder
  vars:
    images:
      - name: custom-caddy
        tag: tkd/caddy
        repo: https://github.com/tierklinik-dobersberg/custom-caddy.git

  tags:
    - image_builder
    - caddy_docker

- name: Create caddy root folder
  file:
    path: /etc/caddy
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Create caddy config folder
  file:
    path: /etc/caddy/config
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Copy root caddy file
  template:
    src: main.caddy.j2
    dest: /etc/caddy/config/main.caddy
    mode: 0755
    owner: root
    group: root
  notify:
    - restart caddy

- name: Create caddy cert folder
  file:
    path: /etc/caddy/certs
    state: directory
    mode: 0700
    owner: root
    group: root

- name: Create caddy logs folder
  file:
    path: /var/log/caddy
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Create caddy webroot
  file:
    path: /var/www
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Create ingress network
  community.general.docker_network:
    name: caddy_ingress
    scope: local
    attachable: true
    driver_options:
      com.docker.network.bridge.name: ingress0

- name: Deploy caddy stack
  include_role:
    name: docker
    tasks_from: "deploy-stack.yml"
  vars:
    stack:
      name: caddy
      path: caddy-stack.yml.j2
