---

- name: Install dotbare
  aur:
    name: dotbare
    state: present
  become: yes
  become_user: aur_builder
  when: aur is defined

- name: Push logrotate config for user logs
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/user
  tags:
    - user
      
- include_tasks: ./configure_user.yml
  with_items: "{{ users }}"
