---
- name: stop systemd per-user instance
  block:
    - name: getent variables
      getent:
        database: passwd

    - name: stop systemd for {getent_passwd[item.name][1]}}
      service:
        name: "user@{{ uid }}"
        state: stopped
      with_items: "{{ users }}"