---
- name: stop systemd per-user instance
  # TODO(ppacher): check why we need the whole path here.
  # looks like a bug in ansible ....
  include: roles/users/handlers/restart-systemd.yml
  with_items: "{{ users }}"