---
- name: getent {{ item.name }} variables
  getent:
    database: passwd
    key: "{{ item.name }}"
    
- set_fact:
    uid: "{{ item.uid | default(getent_passwd[item.name][1]) }}"

- name: stop systemd for {{uid}}
  service:
    name: "user@{{ uid }}"
    state: stopped