---
- name: Install jsondiff
  aur:
    name: python-jsondiff
    state: present
    use: yay
  become: yes
  become_user: aur_builder
  when: stack is defined

- name: Create project directory
  file:
    path: /etc/stacks/{{ stack.name }}
    state: directory
    owner: root
    group: root
    mode: 0755
  when: stack is defined

- name: Deploy stack {{ stack.name }}
  template:
    src: "{{ stack.path }}"
    dest: /etc/stacks/{{ stack.name }}/docker-compose.yml
    mode: 0644
    owner: root
    group: root
  when: stack is defined

- name: Deploy {{ stack.name }} from a compose file
  community.general.docker_compose:
    project_name: "{{ stack.name }}"
    project_src: /etc/stacks/{{ stack.name }}
  when: stack is defined