---
- name: Install docker
  pacman:
    name:
      - docker
      - docker-compose
    state: present
  tags:
    - docker

- name: Enable docker daemon
  service:
    name: docker.service
    enabled: yes
    state: started
  tags:
    - docker