---
- name: Install docker
  pacman:
    name:
      - docker
      - docker-compose
    state: present
  tags:
    - docker

- name: Enable docker daemon
  service:
    name: docker.service
    enabled: yes
    state: started
  tags:
    - docker

- name: Deploy docker-swarm network fix
  copy:
    src: docker-fix-network.service
    dest:  /etc/systemd/system/docker-fix-network.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd config
  when: docker_swarm is defined and docker_swarm.network_fix == True

- name: Enable docker-swarm network fix
  systemd:
    name: docker-fix-network.service
    enabled: yes
    state: started
  when: docker_swarm is defined and docker_swarm.network_fix == True
    
- name: Copy docker-prune.service
  copy:
    src: docker-prune.service
    dest: /etc/systemd/system/docker-prune.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd config
  tags:
    - docker
    
- name: Copy docker-prune.timer
  copy:
    src: docker-prune.timer
    dest: /etc/systemd/system/docker-prune.timer
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd config
    - restart docker-prune.timer
  tags:
    - docker
    
- name: Enable and start docker-prune.timer
  service:
    name: docker-prune.timer
    enabled: yes
    state: started
  tags:
    - docker

- name: Initialize docker swarm node
  community.general.docker_swarm:
    state: present
  when: docker_swarm is defined
  tags:
    - docker

- name: Prepare swarm stacks directory
  file:
    path: /etc/stacks
    state: directory
    mode: 0755
    owner: root
    group: root
  when: docker_swarm is defined
  tags:
    - docker