---
- name: Install sudo
  pacman:
    name: sudo
    state: present
  tags:
    - sudo
      
- name: sudo configuration
  template:
    src: sudoers.j2
    dest: /etc/sudoers
    mode: 440
    validate: 'visudo -cf %s'
  tags:
    - sudo
