---
- name: restart restic-backup timers
  service:
    name: "restic-backup@{{ item.name }}.timer"
    state: restarted
  loop: "{{ backups }}"
  loop_control:
    label: "{{ item.name }}"

- name: restart restic-prune timers
  service:
    name: "restic-prune@{{ item.name }}.timer"
    state: restarted
  loop: "{{ backups }}"
  loop_control:
    label: "{{ item.name }}"